import './globals.css'
import 'highlight.js/styles/github-dark-dimmed.css'
// import { Inter } from 'next/font/google'
import Script from 'next/script'
import UnisatWallectContextProvider from '@/context/unisatWallectContext'
import StyledComponentsRegistry from './../../utils/registry-style'
import clsx from 'clsx'
import { Images } from '@/utils/images'

const systemFont = {
  className: 'system-font',
  style: {
    fontFamily:
      '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Open Sans", "Helvetica Neue", sans-serif',
  },
}
// export async function generateMetadata() {
//   return {
//     openGraph: {
//       title: 'Ordinals', // todo: add inscription number
//       description: 'The Inscription Explorer of Bitcoin.',
//       url: 'https://ordinalscan.net',
//       siteName: 'Ordinals',
//       images: [
//         {
//           url: '/og-image.png',
//           width: 1201,
//           height: 601,
//         },
//       ],
//       locale: 'en-US',
//       type: 'website',
//     },
//   }
// }

const analyze = `
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', 'G-VG49QP1BW1');
`

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      {/*
        <head /> will contain the components returned by the nearest parent
        head.tsx. Find out more at https://beta.nextjs.org/docs/api-reference/file-conventions/head
      */}

      <head>
        {/* todo: add better touch icon for apple */}
        {/* <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.png"
        /> */}
        <title>Ordinals Explorer | Ordinalscan</title>
        <link rel="icon" type="image/svg" sizes="32x32" href={Images.COMMON.ICON_SVG} />
        <link rel="icon" type="image/svg" sizes="16x16" href={Images.COMMON.ICON_SVG} />
        {/* todo: optimize autogenerated web manifest */}
        <link rel="manifest" href={Images.COMMON['SITE_WEBMANIFEST']} />
        <link rel="mask-icon" href={Images.COMMON['SAFARI_PINNED-TAB_SVG']} color="#CFC9C2" />
        <meta name="msapplication-TileColor" content="#CFC9C2" />
        <meta name="theme-color" content="#ffffff" />
        <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0;" name="viewport" />
        <meta
          name="description"
          content="Ordinals explorer, inscriptions, BRC20, tap, collection and domains on Bitcoin."
        />
        {/*{process.env.ENABLE_CSP && (*/}
        {/*  <meta*/}
        {/*    httpEquiv="Content-Security-Policy"*/}
        {/*    content={`frame-src ${*/}
        {/*      process.env.NODE_ENV === 'production' ? '' : ' http://localhost:3000'*/}
        {/*    } https://api.hiro.so https://ordinals.hiro.so https://cdn.ordinalscan.net;`}*/}
        {/*  />*/}
        {/*)}*/}
        <Script async src="https://www.googletagmanager.com/gtag/js?id=G-VG49QP1BW1" />
        <Script id="google-analytics" strategy="afterInteractive" dangerouslySetInnerHTML={{ __html: analyze }} />
        {/* <Script id="google-analytics" strategy="afterInteractive">
          {`(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-PFK4WN9');`}
        </Script> */}
      </head>
      <body className={clsx('flex flex-col justify-between min-h-screen', systemFont.className)}>
        <StyledComponentsRegistry>
          <UnisatWallectContextProvider>{children}</UnisatWallectContextProvider>
        </StyledComponentsRegistry>
        {/* <noscript>
          <iframe
            src="https://www.googletagmanager.com/ns.html?id=GTM-PFK4WN9"
            style={{ display: 'none', visibility: 'hidden' }}
            height="0"
            width="0"
          />
        </noscript> */}
      </body>
    </html>
  )
}
