const ASSETS = {
    'INTER_TTF': '/images/assets/Inter.ttf',
  }
const COMMON = {
    'ACTIVE_BRC20LINK_SVG': '/images/common/active-brc20link.svg',
  'ACTIVE_COLLECTIONS_SVG': '/images/common/active-collections.svg',
  'ANDROID_CHROME-192X192_PNG': '/images/common/android-chrome-192x192.png',
  'ANDROID_CHROME-512X512_PNG': '/images/common/android-chrome-512x512.png',
  'APPLE_TOUCH-ICON_PNG': '/images/common/apple-touch-icon.png',
  'B_ILLUSTRATION_SVG': '/images/common/b-illustration.svg',
  'BIT_DEFAULT_PNG': '/images/common/bit-default.png',
  'BRC20LINK_SVG': '/images/common/brc20Link.svg',
  'BYBIT_PNG': '/images/common/bybit.png',
  'BYBIT_PNG COINGECKO.PNG COINMARKETCAP.PNG GATE.PNG': '/images/common/bybit.png coingecko.png coinmarketcap.png gate.png',
  'COINGECKO_PNG': '/images/common/coingecko.png',
  'COINMARKETCAP_PNG': '/images/common/coinmarketcap.png',
  'COLLECTIONS_SVG': '/images/common/collections.svg',
  'CONNECT_BG_SVG': '/images/common/connect-bg.svg',
  'COPY_SVG': '/images/common/copy.svg',
  'CYPTO_SVG': '/images/common/cypto.svg',
  'DISCONNECT_SVG': '/images/common/disconnect.svg',
  'FAST_GAS_SVG': '/images/common/fast-gas.svg',
  'FAVICON_16X16_PNG': '/images/common/favicon-16x16.png',
  'FAVICON_32X32_PNG': '/images/common/favicon-32x32.png',
  'FAVICON_ICO': '/images/common/favicon.ico',
  'GASICON_SVG': '/images/common/gasIcon.svg',
  'GATE_PNG': '/images/common/gate.png',
  'GITHUB_SVG': '/images/common/github.svg',
  'GREEN_ARROW_SVG': '/images/common/green-arrow.svg',
  'HIRO_DARK_SVG': '/images/common/hiro-dark.svg',
  'HIRO_LIGHT_SVG': '/images/common/hiro-light.svg',
  'HIRO_LOGO-DARK_SVG': '/images/common/hiro-logo-dark.svg',
  'HOTBRC20_SVG': '/images/common/hotbrc20.svg',
  'ICON_MOBILE_SVG': '/images/common/icon-mobile.svg',
  'ICON_SVG': '/images/common/icon.svg',
  'ICON3_SVG': '/images/common/icon3.svg',
  'LOGO_SVG': '/images/common/logo.svg',
  'LOGO2_SVG': '/images/common/logo2.svg',
  'LOW_GAS_SVG': '/images/common/low-gas.svg',
  'MEDIUM_SVG': '/images/common/medium.svg',
  'MIDDLE_GAS_SVG': '/images/common/middle-gas.svg',
  'MINTING_SVG': '/images/common/minting.svg',
  'MOBILE_MENU-ICON_SVG': '/images/common/mobile-menu-icon.svg',
  'MSTILE_144X144_PNG': '/images/common/mstile-144x144.png',
  'MSTILE_150X150_PNG': '/images/common/mstile-150x150.png',
  'MSTILE_310X150_PNG': '/images/common/mstile-310x150.png',
  'MSTILE_310X310_PNG': '/images/common/mstile-310x310.png',
  'MSTILE_70X70_PNG': '/images/common/mstile-70x70.png',
  'MY_ITEMS_SVG': '/images/common/my-items.svg',
  'NEW_CLOSE_SVG': '/images/common/new-close.svg',
  'NEW_SEARCH_SVG': '/images/common/new-search.svg',
  'NOISE_PNG': '/images/common/noise.png',
  'OG_IMAGE_PNG': '/images/common/og-image.png',
  'ORDINAL_ICON_SVG': '/images/common/ordinal-icon.svg',
  'PROJECT_DEFAULT_ICON_PNG': '/images/common/project_default_icon.png',
  'RANK1_SVG': '/images/common/rank1.svg',
  'RANK2_SVG': '/images/common/rank2.svg',
  'RANK3_SVG': '/images/common/rank3.svg',
  'SAFARI_PINNED-TAB_SVG': '/images/common/safari-pinned-tab.svg',
  'SITE_WEBMANIFEST': '/images/common/site.webmanifest',
  'TEXT_PNG': '/images/common/text.png',
  'TRANSICATION_SVG': '/images/common/transication.svg',
  'TWITTER_SVG': '/images/common/twitter.svg',
  'WALLET_ICON_SVG': '/images/common/wallet-icon.svg',
  }
const FONT = {
    'EBRIMA_TTF': '/images/font/ebrima.ttf',
  'EBRIMABD_TTF': '/images/font/ebrimabd.ttf',
  }
const HOME = {
    'ELEMENT_PNG': '/images/home/Element.png',
  'UNISAT_PNG': '/images/home/UniSat.png',
  'BLOCKS_SVG': '/images/home/blocks.svg',
  'BTC_LOGO_SVG': '/images/home/btc_logo.svg',
  'DISCORD_SVG': '/images/home/discord.svg',
  'EMAIL_SVG': '/images/home/email.svg',
  'FEE_SVG': '/images/home/fee.svg',
  'HOME_BANNER_BG_PNG': '/images/home/home-banner_bg.png',
  'IDCLUB_PNG': '/images/home/iDclub.png',
  'INSCRIPTIONS_SVG': '/images/home/inscriptions.svg',
  'ITEMS_GRAY_SVG': '/images/home/items-gray.svg',
  'ITEMS_SVG': '/images/home/items.svg',
  'LOGOUT_GRAY_SVG': '/images/home/logout-gray.svg',
  'LOGOUT_SVG': '/images/home/logout.svg',
  'OWNER_LOGO_SVG': '/images/home/owner_logo.svg',
  'STORE_DATA_SVG': '/images/home/store_data.svg',
  'TOTAL_INSCRIPTION_FEE_SVG': '/images/home/total_inscription_fee.svg',
  'WALLET_ADDRESS_SVG': '/images/home/wallet_address.svg',
  'WEBSITE_SVG': '/images/home/website.svg',
  'WHITELOGO_SVG': '/images/home/whitelogo.svg',
  }
  export const Images = {
    ASSETS,
  COMMON,
  FONT,
  HOME,
  }
  